server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:8083
          predicates:
            - Path=/**
          filters:
            # Этот фильтр используется для передачи токена аутентификации через данный API-шлюз
            # от входящего запроса к исходящему запросу.
            - TokenRelay=
            # Этот фильтр используется для удаления заголовка 'Cookie' из входящего HTTP-запроса
            # перед его перенаправлением на внутренний сервис.
            # Это нужно, чтобы другие сервисы не видели или не использовали куки клиента (опционально)
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        registration:
          gateway:
            # Поставщик аутентификации, типа keycloak, spring и т.д.
            provider: spring
            # Идентификатор клиента
            client-id: gateway
            # Секрет клиента
            client-secret: secret
            # Тип предоставления авторизации (авторизационный код = authorization_code)
            authorization-grant-type: authorization_code
            #  Запрашиваемые scope
            scope:
              - openid
              - message.read
        provider:
          spring:
            issuer-uri: http://localhost:9000
