CREATE TABLE IF NOT EXISTS couriers
(
    courier_id     bigint GENERATED BY DEFAULT AS IDENTITY,
    phone_number   varchar(255) NOT NULL UNIQUE,
    courier_status varchar(255) NOT NULL DEFAULT ('FREE')
        CHECK ( courier_status IN ('HURRIES_TO_ORDER', 'PICKED_UP_THE_ORDER', 'FREE', 'FIRED')),

    PRIMARY KEY (courier_id)
);

CREATE TABLE IF NOT EXISTS coordinates
(
    courier_id bigint REFERENCES couriers (courier_id) ON DELETE CASCADE ON UPDATE NO ACTION,
    latitude   float8 NULL DEFAULT (NULL),
    longitude  float8 NULL DEFAULT (NULL),

    PRIMARY KEY (courier_id)
);



