CREATE TABLE IF NOT EXISTS customers
(
    customer_id    bigint GENERATED BY DEFAULT AS IDENTITY,
    phone_number   varchar(255) NOT NULL UNIQUE,
    customer_email varchar(255) NOT NULL UNIQUE,
    create_date    timestamptz  NOT NULL DEFAULT now(),

    PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS customer_addressees
(
    address_id       bigint GENERATED BY DEFAULT AS IDENTITY,
    customer_id      bigint REFERENCES customers (customer_id) ON DELETE CASCADE ON UPDATE NO ACTION,
    city             varchar(255) NOT NULL,
    street           varchar(255) NOT NULL,
    house_number     smallint     NOT NULL,
    house_section    smallint     NULL DEFAULT (NULL),
    house_floor      smallint     NULL DEFAULT (NULL),
    apartment_number smallint     NULL DEFAULT (NULL),

    PRIMARY KEY (address_id)
);
