CREATE TABLE IF NOT EXISTS restaurants
(
    restaurant_id   bigint GENERATED BY DEFAULT AS IDENTITY,
    restaurant_name varchar(255) UNIQUE NOT NULL,

    PRIMARY KEY (restaurant_id)
);

CREATE TYPE RESTAURANT_STATUS as ENUM ('ACTIVE', 'INACTIVE');

CREATE TABLE IF NOT EXISTS restaurant_address
(
    address_id        bigint GENERATED BY DEFAULT AS IDENTITY,
    street_name       varchar(255)      NOT NULL,
    city              varchar(255)      NOT NULL,
    date_of_add       timestamptz       NOT NULL DEFAULT now(),
    restaurant_status RESTAURANT_STATUS NOT NULL DEFAULT ('ACTIVE'),

    PRIMARY KEY (address_id)
);

CREATE TYPE MENU_ITEM_STATUS as ENUM ('AVAILABLE', 'NOT_AVAILABLE');

CREATE TABLE IF NOT EXISTS menu_items
(
    item_id     bigint GENERATED BY DEFAULT AS IDENTITY,
    item_name   varchar(255)     NOT NULL,
    item_price  numeric(12, 2)   NOT NULL,
    item_status MENU_ITEM_STATUS NOT NULL DEFAULT ('AVAILABLE'),
--     item_image varchar(255) NOT NULL,

    PRIMARY KEY (item_id)
);

ALTER TABLE menu_items
    ALTER COLUMN item_status SET DEFAULT 'AVAILABLE';

CREATE TABLE IF NOT EXISTS restaurants_restaurant_address
(
    restaurant_id bigint,
    address_id    bigint,

    PRIMARY KEY (restaurant_id, address_id),
    CONSTRAINT restaurants_restaurants_restaurant_address_fk
        FOREIGN KEY (restaurant_id) references restaurants (restaurant_id) ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT restaurant_address_restaurants_restaurant_address_fk
        FOREIGN KEY (address_id) references restaurant_address (address_id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS restaurants_menu_items
(
    restaurant_id bigint  NOT NULL,
    item_id       integer NOT NULL,

    PRIMARY KEY (restaurant_id, item_id),
    CONSTRAINT restaurants_menu_items_fk
        FOREIGN KEY (restaurant_id) references restaurants (restaurant_id) ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT menu_items_restaurants_fk
        FOREIGN KEY (item_id) references menu_items (item_id) ON DELETE CASCADE ON UPDATE NO ACTION
);













