CREATE TABLE IF NOT EXISTS customers
(
    customer_id bigint GENERATED BY DEFAULT AS IDENTITY,
    username    varchar(255) NOT NULL UNIQUE,
    password    varchar(255) NOT NULL,
    create_date timestamptz  NOT NULL DEFAULT now(),

    PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS customer_addressees
(
    address_id    bigint GENERATED BY DEFAULT AS IDENTITY,
    city          varchar(255) NOT NULL,
    street        varchar(255) NOT NULL,
    house_number  smallint     NOT NULL,
    house_section smallint     NULL DEFAULT (NULL),
    house_floor   smallint     NOT NULL,

    PRIMARY KEY (address_id)
);

CREATE TABLE IF NOT EXISTS customers_customer_addressees
(
    customer_id bigint,
    address_id  bigint,

    PRIMARY KEY (customer_id, address_id),

    CONSTRAINT customers_customers_customer_addressees_fk
        FOREIGN KEY (customer_id) REFERENCES customers (customer_id) ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT customer_addressees_customers_customer_addressees_fk
        FOREIGN KEY (address_id) REFERENCES customer_addressees (address_id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS customer_order
(
    customer_id bigint,
    order_id    bigint,

    PRIMARY KEY (customer_id, order_id),

    CONSTRAINT customers_customer_oder_fk
        FOREIGN KEY (customer_id) REFERENCES customers (customer_id) ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT orders_customer_order
        FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE ON UPDATE NO ACTION
);














