CREATE TYPE COURIER_STATUS AS ENUM ('HURRIES_TO_ORDER', 'PICKED_UP_THE_ORDER', 'FREE', 'FIRED');

CREATE TABLE IF NOT EXISTS couriers
(
    courier_id     bigint GENERATED BY DEFAULT AS IDENTITY,
    phone_number   varchar(255)   NOT NULL UNIQUE,
    courier_status COURIER_STATUS NOT NULL DEFAULT ('FREE'),

    PRIMARY KEY (courier_id)
);

CREATE TABLE IF NOT EXISTS coordinates
(
    coordinate_id bigint GENERATED BY DEFAULT AS IDENTITY,
    latitude      float8 NULL DEFAULT (NULL),
    longitude     float8 NULL DEFAULT (NULL),

    PRIMARY KEY (coordinate_id)
);

CREATE TABLE IF NOT EXISTS couriers_coordinates
(
    courier_id    bigint,
    coordinate_id bigint,

    PRIMARY KEY (courier_id, coordinate_id),
    CONSTRAINT couriers_couriers_coordinates_fk
        FOREIGN KEY (courier_id) REFERENCES couriers (courier_id) ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT coordinates_couriers_coordinates_fk
        FOREIGN KEY (coordinate_id) REFERENCES coordinates (coordinate_id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS courier_orders
(
    courier_id bigint,
    order_id   bigint,

    PRIMARY KEY (courier_id, order_id),

    CONSTRAINT couriers_courier_orders_fk
        FOREIGN KEY (courier_id) REFERENCES couriers (courier_id) ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT orders_courier_orders_fk
        FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE ON UPDATE NO ACTION
);



